import { packageVersion } from "./paths.js";

export const monoBehaviourKinds = ["image-tracking", "surface-placement", "cloud-recognition", "mega", "lifecycle"] as const;
export const buildPlatforms = ["android", "ios", "standalone", "none"] as const;
export const deviceBuildPlatforms = ["android", "ios", "standalone"] as const;
export const mobilePlatforms = ["android", "ios"] as const;
export const runResultStatuses = ["passed", "failed", "blocked", "not-run"] as const;
export const clientKinds = ["claude-desktop", "codex", "generic-json"] as const;
export const clientEntrypointModes = ["local-dist", "package-bin", "npx"] as const;
export const accountStageValues = ["unknown", "not-registered", "registered-not-logged-in", "logged-in", "has-license", "has-cloud-credentials"] as const;
export type AccountStage = typeof accountStageValues[number];
export const authorizationModeValues = ["auto", "official-api", "local-key", "manual-browser", "local-packages", "stub"] as const;
export type AuthorizationMode = typeof authorizationModeValues[number];
export const serverName = "mcp-easyar";
export const serverVersion = packageVersion;
export const currentGitHubReleaseTag = process.env.MCP_EASYAR_RELEASE_TAG ?? process.env.GITHUB_REF_NAME ?? `v${serverVersion}`;

export const toolCatalog = [
  "easyar_server_status",
  "easyar_list_samples",
  "easyar_official_info",
  "easyar_generate_official_api_contract",
  "easyar_write_official_api_contract",
  "easyar_generate_official_openapi_contract",
  "easyar_write_official_openapi_contract",
  "easyar_official_api_handoff",
  "easyar_write_official_api_handoff",
  "easyar_auth_status",
  "easyar_authorization_strategy",
  "easyar_write_authorization_strategy",
  "easyar_account_onboarding",
  "easyar_write_account_onboarding",
  "easyar_account_materials",
  "easyar_write_account_materials",
  "easyar_portal_evidence",
  "easyar_write_portal_evidence",
  "easyar_check_account",
  "easyar_validate_license",
  "easyar_discover_downloads",
  "easyar_discover_cloud_credentials",
  "easyar_check_official_access",
  "easyar_write_official_access_report",
  "easyar_generate_client_config",
  "easyar_check_client_setup",
  "easyar_write_client_setup",
  "easyar_deployment_readiness",
  "easyar_write_deployment_readiness",
  "easyar_production_validation",
  "easyar_write_production_validation",
  "easyar_write_release_evidence",
  "easyar_release_manifest",
  "easyar_write_release_manifest",
  "easyar_first_run_guide",
  "easyar_write_first_run_guide",
  "easyar_onboarding_report",
  "easyar_write_onboarding_report",
  "easyar_generate_project_handoff",
  "easyar_write_project_handoff",
  "easyar_remaining_work_report",
  "easyar_write_remaining_work_report",
  "easyar_generate_sample_plan",
  "easyar_generate_sample_expansion_plan",
  "easyar_generate_focused_preflight",
  "easyar_write_focused_preflight",
  "easyar_next_workflow_step",
  "easyar_write_workflow_state",
  "easyar_generate_import_checklist",
  "easyar_write_import_checklist",
  "easyar_generate_sample_import_guide",
  "easyar_write_sample_import_guide",
  "easyar_import_sample_from_package_cache",
  "easyar_generate_run_sequence",
  "easyar_write_run_sequence",
  "easyar_generate_artifact_index",
  "easyar_write_artifact_index",
  "easyar_generate_focused_handoff_pack",
  "easyar_write_focused_handoff_pack",
  "easyar_generate_run_report",
  "easyar_write_run_report",
  "easyar_audit_sample_scene",
  "easyar_write_scene_audit",
  "easyar_generate_support_bundle",
  "easyar_write_support_bundle",
  "easyar_list_miniprogram_samples",
  "easyar_check_wechat_devtools",
  "easyar_inspect_miniprogram_project",
  "easyar_generate_miniprogram_local_config_form",
  "easyar_write_miniprogram_local_config_form",
  "easyar_generate_miniprogram_preflight",
  "easyar_write_miniprogram_preflight",
  "easyar_generate_miniprogram_run_sequence",
  "easyar_write_miniprogram_run_sequence",
  "easyar_import_miniprogram_sample_from_local_package",
  "easyar_analyze_miniprogram_devtools_log",
  "easyar_run_miniprogram_devtools_check",
  "easyar_generate_miniprogram_device_validation_checklist",
  "easyar_write_miniprogram_device_validation_checklist",
  "easyar_generate_miniprogram_run_result_form",
  "easyar_write_miniprogram_run_result_form",
  "easyar_write_miniprogram_run_result",
  "easyar_generate_miniprogram_completion_report",
  "easyar_write_miniprogram_completion_report",
  "easyar_generate_miniprogram_run_through_status",
  "easyar_write_miniprogram_run_through_status",
  "easyar_generate_miniprogram_scope_status",
  "easyar_write_miniprogram_scope_status",
  "easyar_generate_device_validation_checklist",
  "easyar_write_device_validation_checklist",
  "easyar_generate_device_run_result_form",
  "easyar_write_device_run_result_form",
  "easyar_generate_android_device_runbook",
  "easyar_write_android_device_runbook",
  "easyar_generate_run_result",
  "easyar_write_run_result",
  "easyar_generate_completion_report",
  "easyar_write_completion_report",
  "easyar_generate_focused_scope_status",
  "easyar_write_focused_scope_status",
  "easyar_generate_issue_report",
  "easyar_write_issue_report",
  "easyar_inspect_unity_project",
  "easyar_check_sample_readiness",
  "easyar_validate_local_config",
  "easyar_generate_local_config_form",
  "easyar_write_local_config_form",
  "easyar_write_local_config_from_env",
  "easyar_local_config_handoff",
  "easyar_write_local_config_handoff",
  "easyar_analyze_unity_log",
  "easyar_analyze_latest_unity_log",
  "easyar_prepare_unity_project",
  "easyar_create_sample_validation_helper",
  "easyar_create_local_config_bridge",
  "easyar_create_mobile_settings_helper",
  "easyar_create_build_settings_helper",
  "easyar_create_device_build_helper",
  "easyar_create_sample_runner",
  "easyar_generate_code_plan",
  "easyar_write_code_plan",
  "easyar_create_mono_behaviour",
  "easyar_write_csharp_file",
  "easyar_generate_config_integration_audit",
  "easyar_write_config_integration_audit",
  "easyar_generate_programming_context",
  "easyar_write_programming_context",
  "easyar_generate_code_change_summary",
  "easyar_write_code_change_summary",
  "easyar_review_csharp_scripts",
  "easyar_unity_environment",
  "easyar_write_unity_environment_report",
  "easyar_run_unity_compile_check",
  "easyar_run_unity_method",
  "easyar_android_device_status",
  "easyar_android_install_apk",
  "easyar_android_start_app",
  "easyar_android_collect_logcat"
] as const;

export const coreToolCatalog = [
  "easyar_server_status",
  "easyar_list_samples",
  "easyar_auth_status",
  "easyar_authorization_strategy",
  "easyar_account_onboarding",
  "easyar_account_materials",
  "easyar_generate_client_config",
  "easyar_check_client_setup",
  "easyar_production_validation",
  "easyar_first_run_guide",
  "easyar_write_first_run_guide",
  "easyar_write_project_handoff",
  "easyar_remaining_work_report",
  "easyar_generate_sample_plan",
  "easyar_generate_sample_expansion_plan",
  "easyar_write_focused_preflight",
  "easyar_next_workflow_step",
  "easyar_write_workflow_state",
  "easyar_write_sample_import_guide",
  "easyar_import_sample_from_package_cache",
  "easyar_write_run_sequence",
  "easyar_write_artifact_index",
  "easyar_write_focused_handoff_pack",
  "easyar_write_run_report",
  "easyar_write_scene_audit",
  "easyar_write_support_bundle",
  "easyar_list_miniprogram_samples",
  "easyar_check_wechat_devtools",
  "easyar_inspect_miniprogram_project",
  "easyar_write_miniprogram_local_config_form",
  "easyar_write_miniprogram_preflight",
  "easyar_write_miniprogram_run_sequence",
  "easyar_import_miniprogram_sample_from_local_package",
  "easyar_analyze_miniprogram_devtools_log",
  "easyar_run_miniprogram_devtools_check",
  "easyar_generate_miniprogram_device_validation_checklist",
  "easyar_write_miniprogram_device_validation_checklist",
  "easyar_generate_miniprogram_run_result_form",
  "easyar_write_miniprogram_run_result_form",
  "easyar_write_miniprogram_run_result",
  "easyar_generate_miniprogram_completion_report",
  "easyar_write_miniprogram_completion_report",
  "easyar_generate_miniprogram_run_through_status",
  "easyar_write_miniprogram_run_through_status",
  "easyar_generate_miniprogram_scope_status",
  "easyar_write_miniprogram_scope_status",
  "easyar_write_device_validation_checklist",
  "easyar_write_device_run_result_form",
  "easyar_write_android_device_runbook",
  "easyar_write_run_result",
  "easyar_write_completion_report",
  "easyar_write_focused_scope_status",
  "easyar_write_issue_report",
  "easyar_inspect_unity_project",
  "easyar_check_sample_readiness",
  "easyar_validate_local_config",
  "easyar_write_local_config_form",
  "easyar_write_local_config_from_env",
  "easyar_write_local_config_handoff",
  "easyar_analyze_unity_log",
  "easyar_analyze_latest_unity_log",
  "easyar_prepare_unity_project",
  "easyar_write_code_plan",
  "easyar_create_mono_behaviour",
  "easyar_write_csharp_file",
  "easyar_write_config_integration_audit",
  "easyar_write_programming_context",
  "easyar_write_code_change_summary",
  "easyar_review_csharp_scripts",
  "easyar_unity_environment",
  "easyar_write_unity_environment_report",
  "easyar_run_unity_compile_check",
  "easyar_run_unity_method",
  "easyar_android_device_status",
  "easyar_android_install_apk",
  "easyar_android_start_app",
  "easyar_android_collect_logcat"
] as const;

export const toolProfile = process.env.MCP_EASYAR_TOOL_PROFILE === "full" ? "full" : "core";
export const coreToolNames = new Set<string>(coreToolCatalog);

export function activeToolCatalog() {
  return toolProfile === "full" ? [...toolCatalog] : [...coreToolCatalog];
}

export const resourceCatalog = [
  "easyar://samples/catalog",
  "easyar://official/info",
  "easyar://official/api-contract",
  "easyar://official/openapi",
  "easyar://client/acceptance",
  "easyar://acceptance/fresh-project",
  "easyar://acceptance/wechat-miniprogram",
  "easyar://status/current",
  "easyar://status/remaining-work",
  "easyar://install/github-release",
  "easyar://release/local-key-mvp",
  "easyar://roadmap",
  "easyar://roadmap/full-goal",
  "easyar://unity/checklist",
  "easyar://workflow/quickstart",
  "easyar://workflow/focused-scope",
  "easyar://workflow/programming",
  "easyar://samples/wechat-miniprogram"
] as const;
